pipeline {
    agent any

    tools {
        // Define Maven configurado en Jenkins como MAVEN_HOME
        maven "MAVEN_HOME"
    }

    stages {
        stage('Clone') {
            steps {
                timeout(time: 2, unit: 'MINUTES') {
                    // Clona desde la rama 'main' del nuevo repositorio
                    git branch: 'main', url: 'https://github.com/Fabri-art/micro-product.git'
                }
            }
        }

        stage('Build') {
            steps {
                timeout(time: 2, unit: 'MINUTES') {
                    // Compila el proyecto sin ejecutar pruebas
                    sh "mvn -DskipTests clean package"
                }
            }
        }

        stage('Test') {
            steps {
                timeout(time: 2, unit: 'MINUTES') {
                    // Ejecuta pruebas y genera reporte (ej. Jacoco)
                    sh "mvn clean install"
                }
            }
        }

        stage('Sonar') {
            steps {
                timeout(time: 2, unit: 'MINUTES') {
                    withSonarQubeEnv('sonarqube') {
                        sh "mvn org.sonarsource.scanner.maven:sonar-maven-plugin:3.9.0.2155:sonar -Pcoverage"
                    }
                }
            }
        }

        stage('Quality gate') {
            steps {
                sleep(10) // Espera inicial

                timeout(time: 10, unit: 'MINUTES') {
                    waitForQualityGate abortPipeline: true
                }
            }
        }

        stage('Deploy') {
            steps {
                echo "Comando de deploy sería algo como: mvn spring-boot:run"
                // Puedes reemplazar esto con tu comando real
                // sh "mvn spring-boot:run"
            }
        }
    }
}
